/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HathoraApi } from "@fern-api/hathora";

export interface CreateRoomResponse {
  roomId: HathoraApi.RoomId;
  host: string;
  port: number;
}
