/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const GetAppResponse: core.serialization.ObjectSchema<
    serializers.GetAppResponse.Raw,
    HathoraApi.GetAppResponse
> = core.serialization
    .object({
        secret: core.serialization.string(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).Deployment));

export declare namespace GetAppResponse {
    interface Raw extends serializers.Deployment.Raw {
        secret: string;
    }
}
