/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HathoraApi } from "@fern-api/hathora";

export interface GetAppResponse extends HathoraApi.Deployment {
  secret: string;
}
