/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeploymentStatus = "running" | "completed" | "failed";

export const DeploymentStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
