/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Region =
  | "ap-northeast-3"
  | "af-south-1"
  | "ap-east-1"
  | "ap-northeast-1"
  | "ap-northeast-2"
  | "ap-south-1"
  | "ap-south-2"
  | "ap-southeast-1"
  | "ap-southeast-2"
  | "ap-southeast-3"
  | "ca-central-1"
  | "eu-central-1"
  | "eu-central-2"
  | "eu-north-1"
  | "eu-south-1"
  | "eu-south-2"
  | "eu-west-1"
  | "eu-west-2"
  | "eu-west-3"
  | "me-central-1"
  | "me-south-1"
  | "sa-east-1"
  | "us-east-1"
  | "us-east-2"
  | "us-west-1"
  | "us-west-2";

export const Region = {
  ApNortheast3: "ap-northeast-3",
  AfSouth1: "af-south-1",
  ApEast1: "ap-east-1",
  ApNortheast1: "ap-northeast-1",
  ApNortheast2: "ap-northeast-2",
  ApSouth1: "ap-south-1",
  ApSouth2: "ap-south-2",
  ApSoutheast1: "ap-southeast-1",
  ApSoutheast2: "ap-southeast-2",
  ApSoutheast3: "ap-southeast-3",
  CaCentral1: "ca-central-1",
  EuCentral1: "eu-central-1",
  EuCentral2: "eu-central-2",
  EuNorth1: "eu-north-1",
  EuSouth1: "eu-south-1",
  EuSouth2: "eu-south-2",
  EuWest1: "eu-west-1",
  EuWest2: "eu-west-2",
  EuWest3: "eu-west-3",
  MeCentral1: "me-central-1",
  MeSouth1: "me-south-1",
  SaEast1: "sa-east-1",
  UsEast1: "us-east-1",
  UsEast2: "us-east-2",
  UsWest1: "us-west-1",
  UsWest2: "us-west-2",
} as const;
