/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class HathoraApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, HathoraApiTimeoutError.prototype);
    }
}
