/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const ConnectToRoomResponse: core.schemas.ObjectSchema<
  serializers.ConnectToRoomResponse.Raw,
  HathoraApi.ConnectToRoomResponse
> = core.schemas.object({
  host: core.schemas.string(),
  port: core.schemas.number(),
});

export declare namespace ConnectToRoomResponse {
  interface Raw {
    host: string;
    port: number;
  }
}
