/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const CreateRoomResponse: core.schemas.ObjectSchema<
  serializers.CreateRoomResponse.Raw,
  HathoraApi.CreateRoomResponse
> = core.schemas.object({
  roomId: core.schemas.lazy(async () => (await import("../..")).RoomId),
  host: core.schemas.string(),
  port: core.schemas.number(),
});

export declare namespace CreateRoomResponse {
  interface Raw {
    roomId: serializers.RoomId.Raw;
    host: string;
    port: number;
  }
}
