/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const DestroyRoomResponse: core.schemas.ObjectSchema<
  serializers.DestroyRoomResponse.Raw,
  HathoraApi.DestroyRoomResponse
> = core.schemas.object({
  destroyed: core.schemas.boolean(),
});

export declare namespace DestroyRoomResponse {
  interface Raw {
    destroyed: boolean;
  }
}
