/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const SuspendRoomResponse: core.schemas.ObjectSchema<
  serializers.SuspendRoomResponse.Raw,
  HathoraApi.SuspendRoomResponse
> = core.schemas.object({
  suspended: core.schemas.boolean(),
});

export declare namespace SuspendRoomResponse {
  interface Raw {
    suspended: boolean;
  }
}
