/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const AppName: core.schemas.Schema<serializers.AppName.Raw, HathoraApi.AppName> = core.schemas.string();

export declare namespace AppName {
  type Raw = string;
}
