/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const Region: core.schemas.Schema<serializers.Region.Raw, HathoraApi.Region> = core.schemas.string();

export declare namespace Region {
  type Raw = string;
}
