/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const RoomId: core.schemas.Schema<serializers.RoomId.Raw, HathoraApi.RoomId> = core.schemas.string();

export declare namespace RoomId {
  type Raw = string;
}
