/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const TransportType: core.schemas.Schema<serializers.TransportType.Raw, HathoraApi.TransportType> =
  core.schemas.enum_(["tcp", "udp"]);

export declare namespace TransportType {
  type Raw = "tcp" | "udp";
}
