/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export const GetAppResponse: core.schemas.ObjectSchema<serializers.GetAppResponse.Raw, HathoraApi.GetAppResponse> =
  core.schemas
    .object({
      secret: core.schemas.string(),
    })
    .extend(core.schemas.lazyObject(async () => (await import("../..")).Deployment));

export declare namespace GetAppResponse {
  interface Raw extends serializers.Deployment.Raw {
    secret: string;
  }
}
