/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export type Response = core.APIResponse<HathoraApi.GetAppResponse, HathoraApi.app.get.Error>;
export type Error = HathoraApi.app.get.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: HathoraApi.app.get.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): HathoraApi.app.get.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<HathoraApi.app.get.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: HathoraApi.app.get.Error._Unknown, visitor: HathoraApi.app.get.Error._Visitor<_Result>) {
      return HathoraApi.app.get.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(value: HathoraApi.app.get.Error, visitor: HathoraApi.app.get.Error._Visitor<_Result>): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
