/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const ConnectToRoomResponse: core.serialization.ObjectSchema<
    serializers.ConnectToRoomResponse.Raw,
    HathoraApi.ConnectToRoomResponse
> = core.serialization.object({
    host: core.serialization.string(),
    port: core.serialization.number(),
});

export declare namespace ConnectToRoomResponse {
    interface Raw {
        host: string;
        port: number;
    }
}
