/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const CreateRoomResponse: core.serialization.ObjectSchema<
    serializers.CreateRoomResponse.Raw,
    HathoraApi.CreateRoomResponse
> = core.serialization.object({
    roomId: core.serialization.lazy(async () => (await import("../../..")).RoomId),
    host: core.serialization.string(),
    port: core.serialization.number(),
});

export declare namespace CreateRoomResponse {
    interface Raw {
        roomId: serializers.RoomId.Raw;
        host: string;
        port: number;
    }
}
