/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const SuspendRoomResponse: core.serialization.ObjectSchema<
    serializers.SuspendRoomResponse.Raw,
    HathoraApi.SuspendRoomResponse
> = core.serialization.object({
    suspended: core.serialization.boolean(),
});

export declare namespace SuspendRoomResponse {
    interface Raw {
        suspended: boolean;
    }
}
