/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { HathoraApi } from "@fern-api/hathora";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.HathoraApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    public async get(appName: HathoraApi.AppName): Promise<HathoraApi.GetAppResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.HathoraApiEnvironment.Production, `/app/${appName}/`),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.app.get.Response.parse(_response.body as serializers.app.get.Response.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.HathoraApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.HathoraApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.HathoraApiTimeoutError();
            case "unknown":
                throw new errors.HathoraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async logs(appName: HathoraApi.AppName): Promise<string> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.HathoraApiEnvironment.Production,
                `/app/${appName}/logs`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.app.logs.Response.parse(_response.body as serializers.app.logs.Response.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.HathoraApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.HathoraApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.HathoraApiTimeoutError();
            case "unknown":
                throw new errors.HathoraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async delete(appName: HathoraApi.AppName, request?: HathoraApi.GetAppRequest): Promise<string> {
        const _queryParams = new URLSearchParams();
        if (request?.forceDestroy != null) {
            _queryParams.append("forceDestroy", request?.forceDestroy.toString());
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.HathoraApiEnvironment.Production,
                `/app/${appName}/delete`
            ),
            method: "DELETE",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.app.delete.Response.parse(_response.body as serializers.app.delete.Response.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.HathoraApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.HathoraApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.HathoraApiTimeoutError();
            case "unknown":
                throw new errors.HathoraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
