/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../core";

export type Response = core.APIResponse<HathoraApi.SuspendRoomResponse, HathoraApi.room.suspend.Error>;
export type Error = HathoraApi.room.suspend.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: HathoraApi.room.suspend.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): HathoraApi.room.suspend.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<HathoraApi.room.suspend.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: HathoraApi.room.suspend.Error._Unknown, visitor: HathoraApi.room.suspend.Error._Visitor<_Result>) {
      return HathoraApi.room.suspend.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: HathoraApi.room.suspend.Error,
    visitor: HathoraApi.room.suspend.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
