/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HathoraApi } from "@fern-api/hathora";

export interface Deployment {
    appId: HathoraApi.AppId;
    deploymentId: HathoraApi.DeploymentId;
    regionalContainerTags: HathoraApi.RegionalContainerTags[];
    containerPort: number;
    transportType: HathoraApi.TransportType;
    roomsPerProcess: number;
    requestedCpu: number;
    requestedMemoryMb: number;
    deployedBy: string;
    deployStartedAt: Date;
    deployFinishedAt?: Date;
    status: HathoraApi.DeploymentStatus;
}
