/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const HathoraApiEnvironment = {
    Production: "https://cloud.hathora.dev/v1/",
} as const;

export type HathoraApiEnvironment = typeof HathoraApiEnvironment.Production;
