/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://cloud.hathora.dev/v1/",
} as const;

export type Environment = typeof Environment.Production;
