/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.app.logs.Response.Raw, string> = core.schemas.string();

export declare namespace Response {
  type Raw = string;
}
