/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const DeploymentId: core.serialization.Schema<serializers.DeploymentId.Raw, HathoraApi.DeploymentId> =
    core.serialization.string();

export declare namespace DeploymentId {
    type Raw = string;
}
