/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HathoraApi } from "@fern-api/hathora";
import * as core from "../../../../core";

export const DeploymentStatus: core.serialization.Schema<
    serializers.DeploymentStatus.Raw,
    HathoraApi.DeploymentStatus
> = core.serialization.enum_(["running", "completed", "failed"]);

export declare namespace DeploymentStatus {
    type Raw = "running" | "completed" | "failed";
}
